USE DBCITE
GO

INSERT INTO ROL (DESC_ROL, ROL_USUARIO) 
VALUES ('Rol usuario CITE','ROLE_CITE')

GO
INSERT INTO ROL (DESC_ROL, ROL_USUARIO) 
VALUES ('Rol usuario ADMINISTRADOR','ROLE_ADMIN')
GO

INSERT INTO TIPO_USUARIO (NOMBRE_TIPO_USUARIO, ESTADO) 
VALUES ('ROLE_CITE','1')
GO

INSERT INTO TIPO_USUARIO (NOMBRE_TIPO_USUARIO, ESTADO) 
VALUES ('ROLE_ADMIN','1')
GO

--SE INSERTA EL USUARIO ADMIN INICIAL
INSERT INTO USUARIO (ID_USUARIO,CONTRASENIA, NOMBRES, TIPO_USUARIO, ESTADO)
VALUES('ADMINCITE', '601f1889667efaebb33b8c12572835da3f027f78','USUARIO ADMIN', '2', '1')



